//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookGroup
    {
        public BookGroup()
        {
            this.Books = new HashSet<Book>();
            this.Tr_Details = new HashSet<Tr_Details>();
        }
    
        public int BookGroupID { get; set; }
        public string MainBookName { get; set; }
        public string Class { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
        public virtual ICollection<Tr_Details> Tr_Details { get; set; }
    }
}
