//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Tr_Details = new HashSet<Tr_Details>();
        }
    
        public int BookID { get; set; }
        public Nullable<int> BookGroupID { get; set; }
        public string BookName { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Commission { get; set; }
        public Nullable<int> BookOpnBalance { get; set; }
        public string AuthorName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> ReturnRate { get; set; }
        public Nullable<int> BookForma { get; set; }
    
        public virtual BookGroup BookGroup { get; set; }
        public virtual ICollection<Tr_Details> Tr_Details { get; set; }
    }
}
