//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Tr_Masters = new HashSet<Tr_Masters>();
        }
    
        public int ClientID { get; set; }
        public string ClientName { get; set; }
        public string Address { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public Nullable<int> ClientOpnBalance { get; set; }
        public string ClientType { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
    
        public virtual District District { get; set; }
        public virtual ICollection<Tr_Masters> Tr_Masters { get; set; }
    }
}
