//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.Clients = new HashSet<Client>();
            this.Tr_Masters = new HashSet<Tr_Masters>();
        }
    
        public int DistrictID { get; set; }
        public string DistrictName { get; set; }
        public Nullable<int> DivisionID { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
        public virtual Division Division { get; set; }
        public virtual ICollection<Tr_Masters> Tr_Masters { get; set; }
    }
}
