//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyReceipt
    {
        public int MR_ID { get; set; }
        public string MR_No { get; set; }
        public Nullable<int> Tr_MasterID { get; set; }
        public Nullable<int> PartyCode { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Tr_Masters Tr_Masters { get; set; }
    }
}
