//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Tr_DBEntities : DbContext
    {
        public Tr_DBEntities()
            : base("name=Tr_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookGroup> BookGroups { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<MoneyReceipt> MoneyReceipts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tr_Details> Tr_Details { get; set; }
        public virtual DbSet<Tr_Masters> Tr_Masters { get; set; }
    
        public virtual ObjectResult<sp_Tr_MasterDetail_Result> sp_Tr_MasterDetail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Tr_MasterDetail_Result>("sp_Tr_MasterDetail");
        }
    }
}
