//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tr_Details
    {
        public int Tr_DetailID { get; set; }
        public int Tr_MasterID { get; set; }
        public Nullable<int> BookGroupID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual BookGroup BookGroup { get; set; }
        public virtual Book Book { get; set; }
        public virtual Tr_Masters Tr_Masters { get; set; }
    }
}
