//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tr_Masters
    {
        public Tr_Masters()
        {
            this.MoneyReceipts = new HashSet<MoneyReceipt>();
            this.Tr_Details = new HashSet<Tr_Details>();
        }
    
        public int Tr_MasterID { get; set; }
        public Nullable<System.DateTime> Tr_Date { get; set; }
        public string SL_NO { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> PackDebit { get; set; }
        public Nullable<int> Less { get; set; }
        public string Type { get; set; }
        public string ReturnLessMemoNo { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public Nullable<int> BindID { get; set; }
        public string OrderID { get; set; }
        public Nullable<int> Commission { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual District District { get; set; }
        public virtual ICollection<MoneyReceipt> MoneyReceipts { get; set; }
        public virtual ICollection<Tr_Details> Tr_Details { get; set; }
    }
}
